#using virions: libasynql
name: InventoryConnect
main: RoMo\InventoryConnect\InventoryConnect
author: RoMo_Official
version: 1.4.1
api:
  - 5.0.0

depend:
  - StarGate-Atlantis
  - XuidCore

softdepend:
  - SqlCore

virions:
  - poggit/libasynql/master